-- Bundler: src/ + init.lua -> dist/uai.lua, the single file a user runs.
--
--   luajit tools/bundle.lua
--
-- Each module's source is emitted verbatim inside an immediately-invoked function,
-- so what ships is the code that was written and reviewed -- no rewriting, no
-- minification, and a stack trace still names the module it came from. A header
-- comment records the manifest so the artifact can be identified after the fact.
package.path = "test/?.lua;" .. package.path
local luau = require("luau")

local WINDOWS = package.config:sub(1, 1) == "\\"

local function listFiles(dir)
	local out = {}
	local command = WINDOWS
		and ('dir /b /s "' .. dir:gsub("/", "\\") .. '\\*.lua" 2>nul')
		or ('find "' .. dir .. '" -name "*.lua" -type f 2>/dev/null')
	local pipe = io.popen(command)
	if not pipe then return out end
	for line in pipe:lines() do
		local clean = line:gsub("\\", "/"):gsub("%s+$", "")
		if clean ~= "" then out[#out + 1] = clean end
	end
	pipe:close()
	table.sort(out)
	return out
end

local function read(path)
	local handle = io.open(path, "rb")
	if not handle then return nil end
	local body = handle:read("*a")
	handle:close()
	return body
end

local function write(path, body)
	local handle = io.open(path, "wb")
	if not handle then return false, "cannot open " .. path end
	handle:write(body)
	handle:close()
	return true
end

-- Dependency order is not needed -- every module is a factory that is only called
-- on first require -- but a stable order keeps the artifact byte-identical between
-- builds, which makes a diff meaningful.
local modules = {}
for _, path in ipairs(listFiles("src")) do
	local id = path:match(".*/src/(.+)%.lua$") or path:match("^src/(.+)%.lua$")
	if id then
		local source = read(path)
		if not source then
			io.stderr:write("cannot read " .. path .. "\n")
			os.exit(1)
		end
		local fn, problems = luau.load(source, id)
		if not fn then
			io.stderr:write("bundle refused: " .. id .. " does not pass the checker\n")
			for _, problem in ipairs(problems or {}) do
				io.stderr:write(string.format("  %s:%d: %s\n", id, problem.line or 0, problem.msg or "?"))
			end
			os.exit(1)
		end
		modules[#modules + 1] = { id = id, source = source, bytes = #source }
	end
end

if #modules == 0 then
	io.stderr:write("no modules found under src/\n")
	os.exit(1)
end

local bootSource = read("init.lua")
if not bootSource then
	io.stderr:write("init.lua is missing\n")
	os.exit(1)
end
do
	local fn, problems = luau.load(bootSource, "init.lua", { entry = true })
	if not fn then
		io.stderr:write("bundle refused: init.lua does not pass the checker\n")
		for _, problem in ipairs(problems or {}) do
			io.stderr:write(string.format("  init.lua:%d: %s\n", problem.line or 0, problem.msg or "?"))
		end
		os.exit(1)
	end
end

local version = bootSource:match('local VERSION = "([^"]+)"') or "0.0.0"

local out = {}
local function emit(line)
	out[#out + 1] = line
end

local total = 0
for _, module in ipairs(modules) do total = total + module.bytes end

emit("-- Project UAI " .. version .. " -- a universal Roblox AI agent client.")
emit("--")
emit("-- Generated by tools/bundle.lua. Do not edit: change src/ and rebuild.")
emit(string.format("-- %d modules, %d bytes of source.", #modules, total))
emit("--")
emit("-- Usage:")
emit('--     loadstring(game:HttpGet("<url>/dist/uai.lua"))()')
emit("--")
for _, module in ipairs(modules) do
	emit(string.format("--   %-28s %6d bytes", module.id, module.bytes))
end
emit("")
emit("local __UAI_MODULES = {}")
emit("")

for _, module in ipairs(modules) do
	emit(("-- "):rep(1) .. ("="):rep(74))
	emit("-- " .. module.id)
	emit(("-- "):rep(1) .. ("="):rep(74))
	emit(string.format('__UAI_MODULES["%s"] = (function()', module.id))
	emit(module.source:gsub("\r\n", "\n"):gsub("%s+$", ""))
	emit("end)()")
	emit("")
end

emit(("-- "):rep(1) .. ("="):rep(74))
emit("-- bootstrap")
emit(("-- "):rep(1) .. ("="):rep(74))
emit(bootSource:gsub("\r\n", "\n"):gsub("%s+$", ""))
emit("")

local bundle = table.concat(out, "\n")

-- The bundle has to parse as one chunk, or a syntax error in one module becomes a
-- mystery at load time in a game.
local check, problems = luau.load(bundle, "dist/uai.lua", { entry = true })
if not check then
	io.stderr:write("the assembled bundle does not parse:\n")
	for _, problem in ipairs(problems or {}) do
		io.stderr:write(string.format("  dist/uai.lua:%d: %s\n", problem.line or 0, problem.msg or "?"))
	end
	os.exit(1)
end

os.execute(WINDOWS and "if not exist dist mkdir dist" or "mkdir -p dist")
local ok, err = write("dist/uai.lua", bundle)
if not ok then
	io.stderr:write(tostring(err) .. "\n")
	os.exit(1)
end

print(string.format("dist/uai.lua written: %d modules, %d bytes", #modules, #bundle))
